### ISSUE TITLE
ReferenceManyInput

### ISSUE THREAD

**Issue by matteo-s** [smartcommunitylab/react-admin-packages#1]
edit reference arrays with list in context + dialog for add.

**Comment by claudioballardini01** [comment]
ReferenceManyInput: component designed for the editing phase of a resource. This component facilitates the updating of an array field containing the keys  of another resource, whose instances are associated with the resource to edit through a one-to-many relationship. The schematic representation below illustrates that each referenced element corresponds to a row within a table. This table is equipped with pagination, sorting, and filtering capabilities.


![IMG20231003114134](https://github.com/smartcommunitylab/react-admin-packages/assets/38256821/0a6053c0-60a9-4059-8fae-5491b4829b6a)


Within each row, users will find a checkbox and a "Remove" button, intended for removing the associated entry from the list.  This component offers only a bulk action: the removal of the entries with the checkbox selected.

Additionally, the component features an "Add" button, which enables the addition of new elements. Upon clicking this button, a modal window appears, displaying a list that encompasses all elements related to the referenced resource. This list also offers pagination, sorting, and filtering functionalities. At the bottom of the modal, there are two buttons: "Cancel" and "Add". Each row within the list contains a checkbox and, when the user selects the "Add" button, the entries with checkbox selected are incorporated into the table of referenced elements.

Any modifications are sent to the server when the user click the "Save" button.
